# Generated by Django 5.2.7 on 2025-10-03 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('radio_blackout', 'Radio Blackout'), ('solar_flare', 'Solar Flare'), ('geomagnetic_storm', 'Geomagnetic Storm'), ('solar_radiation', 'Solar Radiation Storm')], max_length=20)),
                ('severity', models.CharField(choices=[('R1', 'R1 - Minor'), ('R2', 'R2 - Moderate'), ('R3', 'R3 - Strong'), ('R4', 'R4 - Severe'), ('R5', 'R5 - Extreme'), ('M', 'M-Class Flare'), ('X', 'X-Class Flare'), ('G1', 'G1 - Minor Storm'), ('G2', 'G2 - Moderate Storm'), ('G3', 'G3 - Strong Storm'), ('G4', 'G4 - Severe Storm'), ('G5', 'G5 - Extreme Storm')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('relevant_for_farmers', models.BooleanField(default=False)),
                ('relevant_for_pilots', models.BooleanField(default=False)),
                ('relevant_for_stargazers', models.BooleanField(default=False)),
                ('relevant_for_educators', models.BooleanField(default=False)),
                ('relevant_for_general', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solar Alert',
                'verbose_name_plural': 'Solar Alerts',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='profiles_so_detecte_9e8404_idx'), models.Index(fields=['is_active'], name='profiles_so_is_acti_a3d1fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('stargazer', 'Stargazer'), ('farmer', 'Farmer'), ('pilot', 'Pilot'), ('educator', 'Educator'), ('general', 'General Interest')], default='general', help_text='Select your interest or profession for targeted space weather alerts', max_length=20)),
                ('receive_alerts', models.BooleanField(default=True, help_text='Receive space weather alerts relevant to your interests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
