# Generated by Django 5.2.7 on 2025-10-03 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, choices=[('stargazer', 'Stargazer'), ('farmer', 'Farmer'), ('pilot', 'Pilot'), ('educator', 'Educator')], default='', help_text='Select your primary interest/profession to tailor alerts.', max_length=20)),
                ('alert_opt_in', models.BooleanField(default=True, help_text='Receive targeted space weather alerts relevant to you.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
